export type Trainer = {
  id: number
  name: string
  title: string
  specialization: string
  experience: string
  rating: number
  reviews: number
  location: string
  image: string
  certifications: string[]
  languages: string[]
  price: string
  availability: string
  bio: string
  specialty: string
  verified?: boolean
  highlights?: string[]
  healthConditions?: string[]
  sessions?: number
  successRate?: string
}

export const trainers: Trainer[] = [
  {
    id: 1,
    name: "Sikha Bansal",
    title: "Senior Yoga Instructor",
    specialization: "Hatha & Vinyasa Yoga",
    experience: "8 years",
    rating: 4.9,
    reviews: 156,
    location: "Mumbai, Pune",
    image: "/t1.jpg?height=400&width=400&text=Priya+Sharma+Yoga+Instructor",
    certifications: ["RYT-500", "Meditation Teacher", "Ayurveda Certified"],
    languages: ["Hindi", "English", "Marathi"],
    price: "₹1,200",
    availability: "Mon-Sat",
    bio: "Passionate about helping students find balance through traditional yoga practices combined with modern wellness techniques.",
    specialty: "Stress Relief & Flexibility",
    verified: true,
    highlights: ["Stress Relief", "Flexibility", "Traditional Yoga"],
    healthConditions: ["Anxiety", "Depression", "Stress Relief", "Mental Strength", "Relaxation", "Sleep Wellness"],
  },
  {
    id: 2,
    name: "Manoj Bansal",
    title: "Power Yoga Specialist",
    specialization: "Power Yoga & Meditation",
    experience: "12 years",
    rating: 4.8,
    reviews: 203,
    location: "Delhi, Gurgaon",
    image: "/t2.jpg?height=400&width=400&text=Rajesh+Kumar+Power+Yoga",
    certifications: ["RYT-200", "Power Yoga Specialist", "Mindfulness Coach"],
    languages: ["Hindi", "English", "Punjabi"],
    price: "₹1,500",
    availability: "All days",
    bio: "Specializes in dynamic yoga flows and meditation techniques for stress management and mental clarity.",
    specialty: "Power Yoga & Mental Clarity",
    sessions: 1800,
    successRate: "96%",
    verified: true,
    highlights: ["Power Yoga", "Mental Clarity", "Dynamic Flows"],
    healthConditions: ["Increased Energy", "Stamina", "Mental Strength", "Lifestyle Diseases", "Diabetes", "Immunity"],
  },
  {
    id: 3,
    name: "Kishan Panwar",
    title: "Wellness & Prenatal Expert",
    specialization: "Prenatal & Restorative Yoga",
    experience: "10 years",
    rating: 5.0,
    reviews: 89,
    location: "Bangalore",
    image: "/t3.jpg?height=400&width=400&text=Anita+Patel+Prenatal+Yoga",
    certifications: ["Prenatal Yoga Certified", "Yin Yoga Teacher", "Therapeutic Yoga"],
    languages: ["English", "Tamil", "Kannada"],
    price: "₹1,000",
    availability: "Mon-Fri",
    bio: "Dedicated to supporting women through their wellness journey with gentle, healing yoga practices.",
    specialty: "Prenatal & Therapeutic",
    sessions: 950,
    successRate: "100%",
    verified: false,
    highlights: ["Prenatal Care", "Therapeutic Yoga", " Wellness"],
    healthConditions: [
      "Anti Aging",
      "Anxiety",
      "Arthritis",
      "Depression",
      "Detoxification",
      "Diabetes",
      "Digestive Disorders",
      "Immunity",
      "Increased Energy",
      "Lifestyle Diseases",
      "Mental Strength",
      "Headaches",
      "Rejuvenation",
      "Relaxation",
      "Sleep Wellness",
      "Stamina",
      "Stress Relief",
    ],
  },
  {
    id: 4,
    name: "Jacks Maliyakal",
    title: "Master Yoga Teacher",
    specialization: "Ashtanga & Advanced Yoga",
    experience: "15 years",
    rating: 4.9,
    reviews: 267,
    location: "Jaipur, Udaipur",
    image: "/t4.jpg?height=400&width=400&text=Vikram+Singh+Ashtanga+Master",
    certifications: ["Ashtanga Authorized", "Advanced Yoga Teacher", "Philosophy Teacher"],
    languages: ["Hindi", "English", "Rajasthani"],
    price: "₹1,800",
    availability: "Tue-Sun",
    bio: "Master practitioner of traditional Ashtanga yoga with deep knowledge of yogic philosophy and advanced techniques.",
    specialty: "Advanced Practices",
    sessions: 2200,
    successRate: "97%",
    verified: true,
    highlights: ["Advanced Yoga", "Ashtanga", "Philosophy"],
    healthConditions: ["Arthritis", "Headaches", "Immunity", "Stamina", "Mental Strength", "Lifestyle Diseases"],
  },
  {
    id: 4,
    name: "Jacks Maliyakal",
    title: "Master Yoga Teacher",
    specialization: "Ashtanga & Advanced Yoga",
    experience: "15 years",
    rating: 4.9,
    reviews: 267,
    location: "Jaipur, Udaipur",
    image: "/t4.jpg?height=400&width=400&text=Vikram+Singh+Ashtanga+Master",
    certifications: ["Ashtanga Authorized", "Advanced Yoga Teacher", "Philosophy Teacher"],
    languages: ["Hindi", "English", "Rajasthani"],
    price: "₹1,800",
    availability: "Tue-Sun",
    bio: "Master practitioner of traditional Ashtanga yoga with deep knowledge of yogic philosophy and advanced techniques.",
    specialty: "Advanced Practices",
    sessions: 2200,
    successRate: "97%",
    verified: true,
    highlights: ["Advanced Yoga", "Ashtanga", "Philosophy"],
    healthConditions: ["Arthritis", "Headaches", "Immunity", "Stamina", "Mental Strength", "Lifestyle Diseases"],
  },
  {
    id: 5,
    name: "Jacks Maliyakal",
    title: "Master Yoga Teacher",
    specialization: "Ashtanga & Advanced Yoga",
    experience: "15 years",
    rating: 4.9,
    reviews: 267,
    location: "Jaipur, Udaipur",
    image: "/t4.jpg?height=400&width=400&text=Vikram+Singh+Ashtanga+Master",
    certifications: ["Ashtanga Authorized", "Advanced Yoga Teacher", "Philosophy Teacher"],
    languages: ["Hindi", "English", "Rajasthani"],
    price: "₹1,800",
    availability: "Tue-Sun",
    bio: "Master practitioner of traditional Ashtanga yoga with deep knowledge of yogic philosophy and advanced techniques.",
    specialty: "Advanced Practices",
    sessions: 2200,
    successRate: "97%",
    verified: true,
    highlights: ["Advanced Yoga", "Ashtanga", "Philosophy"],
    healthConditions: ["Arthritis", "Headaches", "Immunity", "Stamina", "Mental Strength", "Lifestyle Diseases"],
  },
  {
    id: 6,
    name: "Jacks Maliyakal",
    title: "Master Yoga Teacher",
    specialization: "Ashtanga & Advanced Yoga",
    experience: "15 years",
    rating: 4.9,
    reviews: 267,
    location: "Jaipur, Udaipur",
    image: "/t4.jpg?height=400&width=400&text=Vikram+Singh+Ashtanga+Master",
    certifications: ["Ashtanga Authorized", "Advanced Yoga Teacher", "Philosophy Teacher"],
    languages: ["Hindi", "English", "Rajasthani"],
    price: "₹1,800",
    availability: "Tue-Sun",
    bio: "Master practitioner of traditional Ashtanga yoga with deep knowledge of yogic philosophy and advanced techniques.",
    specialty: "Advanced Practices",
    sessions: 2200,
    successRate: "97%",
    verified: true,
    highlights: ["Advanced Yoga", "Ashtanga", "Philosophy"],
    healthConditions: ["Arthritis", "Headaches", "Immunity", "Stamina", "Mental Strength", "Lifestyle Diseases"],
  },
  {
    id: 7,
    name: "Jacks Maliyakal",
    title: "Master Yoga Teacher",
    specialization: "Ashtanga & Advanced Yoga",
    experience: "15 years",
    rating: 4.9,
    reviews: 267,
    location: "Jaipur, Udaipur",
    image: "/t4.jpg?height=400&width=400&text=Vikram+Singh+Ashtanga+Master",
    certifications: ["Ashtanga Authorized", "Advanced Yoga Teacher", "Philosophy Teacher"],
    languages: ["Hindi", "English", "Rajasthani"],
    price: "₹1,800",
    availability: "Tue-Sun",
    bio: "Master practitioner of traditional Ashtanga yoga with deep knowledge of yogic philosophy and advanced techniques.",
    specialty: "Advanced Practices",
    sessions: 2200,
    successRate: "97%",
    verified: true,
    highlights: ["Advanced Yoga", "Ashtanga", "Philosophy"],
    healthConditions: ["Arthritis", "Headaches", "Immunity", "Stamina", "Mental Strength", "Lifestyle Diseases"],
  },
]
